### OR Function

In [1]:
# 패키지 불러오기
import numpy as np

In [2]:
# OR 함수 
X = np.array([[0,0],[0,1],[1,0],[1,1]])

y = np.array([[0],[1],[1],[1]])

print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [1]]


In [3]:
# deep learning
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Activation, Dense

In [4]:
# 모델 생성하기
model = keras.Sequential()

model.add(Dense(input_dim = 2, units = 1)) #feature = 0 or 1(2개)
model.add(Activation('sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer = 'sgd')

model.fit(X,y, batch_size = 1, epochs = 100)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 1.2327
Epoch 2/100
4/4 [==============================] - 0s 848us/step - loss: 1.1495
Epoch 3/100
4/4 [==============================] - 0s 855us/step - loss: 0.9678
Epoch 4/100
4/4 [==============================] - 0s 874us/step - loss: 1.1289
Epoch 5/100
4/4 [==============================] - 0s 1ms/step - loss: 1.0951
Epoch 6/100
4/4 [==============================] - 0s 847us/step - loss: 0.9089
Epoch 7/100
4/4 [==============================] - 0s 873us/step - loss: 0.8960
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 1.0433
Epoch 9/100
4/4 [==============================] - 0s 834us/step - loss: 0.9597
Epoch 10/100
4/4 [==============================] - 0s 879us/step - loss: 0.8816
Epoch 11/100
4/4 [==============================] - 0s 857us/step - loss: 0.9104
Epoch 12/100
4/4 [==============================] - 0s 1ms/step - loss: 0.9370
Epoch 13/100
4/4 [===========================

In [5]:
# 모델 생성하기
model1 = keras.Sequential()

model1.add(Dense(input_dim = 2, units = 1)) #feature = 0 or 1(2개)
model1.add(Activation('sigmoid'))

model1.compile(loss = 'binary_crossentropy', optimizer = 'adam')

model1.fit(X,y, batch_size = 1, epochs = 100)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 0.9366
Epoch 2/100
4/4 [==============================] - 0s 927us/step - loss: 1.3444
Epoch 3/100
4/4 [==============================] - 0s 881us/step - loss: 1.3398
Epoch 4/100
4/4 [==============================] - 0s 898us/step - loss: 1.0172
Epoch 5/100
4/4 [==============================] - 0s 902us/step - loss: 1.2471
Epoch 6/100
4/4 [==============================] - 0s 822us/step - loss: 0.9256
Epoch 7/100
4/4 [==============================] - 0s 1ms/step - loss: 1.0108
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 1.1777
Epoch 9/100
4/4 [==============================] - 0s 916us/step - loss: 1.1765
Epoch 10/100
4/4 [==============================] - 0s 1ms/step - loss: 1.0058
Epoch 11/100
4/4 [==============================] - 0s 1ms/step - loss: 0.9186
Epoch 12/100
4/4 [==============================] - 0s 988us/step - loss: 0.9111
Epoch 13/100
4/4 [=============================

In [6]:
test_data = np.array([[0,1], [0,0], [1,1]]) # 1,0,1
print('sgd:\n', model.predict(test_data))
print('sgd:\n',model.predict_classes(test_data))
print('adam:\n', model1.predict(test_data))
print('adam:\n',model1.predict_classes(test_data))

sgd:
 [[0.7440977 ]
 [0.66426253]
 [0.7607093 ]]
sgd:
 [[1]
 [1]
 [1]]
adam:
 [[0.6122554 ]
 [0.55393875]
 [0.35045648]]
adam:
 [[1]
 [1]
 [0]]


/anaconda/envs/azureml_py36_tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [7]:
# 모델 생성하기
model2 = keras.Sequential()

model2.add(Dense(input_dim = 2, units = 1)) #feature = 0 or 1(2개)
model2.add(Activation('sigmoid'))

sgd= keras.optimizers.SGD(lr = 9)

model2.compile(loss = 'binary_crossentropy', optimizer = sgd)

model2.fit(X,y, batch_size = 1, epochs = 100)

Epoch 1/100
4/4 [==============================] - 0s 2ms/step - loss: 0.5139
Epoch 2/100
4/4 [==============================] - 0s 797us/step - loss: 3.3837
Epoch 3/100
4/4 [==============================] - 0s 793us/step - loss: 0.2473
Epoch 4/100
4/4 [==============================] - 0s 821us/step - loss: 0.0057
Epoch 5/100
4/4 [==============================] - 0s 749us/step - loss: 0.0034
Epoch 6/100
4/4 [==============================] - 0s 814us/step - loss: 0.0073
Epoch 7/100
4/4 [==============================] - 0s 835us/step - loss: 0.0035
Epoch 8/100
4/4 [==============================] - 0s 790us/step - loss: 0.0044
Epoch 9/100
4/4 [==============================] - 0s 865us/step - loss: 0.0040
Epoch 10/100
4/4 [==============================] - 0s 903us/step - loss: 0.0026
Epoch 11/100
4/4 [==============================] - 0s 862us/step - loss: 0.0027
Epoch 12/100
4/4 [==============================] - 0s 891us/step - loss: 0.0039
Epoch 13/100
4/4 [=====================

In [8]:
print('sgd_lr_0.1:\n', model2.predict(test_data))
print('sgd_lr_0.1:\n',model2.predict_classes(test_data))

sgd_lr_0.1:
 [[0.9988303 ]
 [0.00324395]
 [1.        ]]
sgd_lr_0.1:
 [[1]
 [0]
 [1]]


* Adam과 SGD의 차이
* learning rate를 높게 해줘야 예측률이 향상
* learning rate의 범위는 0이상