### 딥-러닝 과정 Mulit Layer Perceptron(MLP) 
[Notion_And Function](https://www.notion.so/mongmang/And-Function-80d9257921064e08990d929aaa1c5169)

## Simple Keras 모델 생성/학습 - AND Function

In [1]:
# 1. Numpy 가져오기
import numpy as np
print(np.__version__)

1.19.5


In [2]:
# 2. And function: 입력/출력 데이터 만들기
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0],[0],[0],[1]])

print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [3]:
# 3. Keras 패키지 가져오기
from tensorflow import keras
from tensorflow.keras import layers
from keras.layers import Activation, Dense

print(keras.__version__)

2.4.0


In [4]:
# 4. Perceptron 모델 생성
# 모델 생성 및 모델 초기화
model = keras.Sequential()

In [5]:
model.add(Dense(input_dim = 2, units = 1)) #feature = 0 or 1(2개)
model.add(Activation('sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [6]:
# 5. Compile - Optimizer, Loss function 설정
model.compile(loss = 'binary_crossentropy', optimizer = 'sgd')

In [7]:
# 6. 학습시키기
model.fit(X, y,
          batch_size = 1, # 1개마다 답확인
          epochs = 100) # 100번 반복 => 4개  데이터 * 100 

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6331
Epoch 2/100
4/4 [==============================] - 0s 1ms/step - loss: 0.8735
Epoch 3/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7622
Epoch 4/100
4/4 [==============================] - 0s 812us/step - loss: 0.7603
Epoch 5/100
4/4 [==============================] - 0s 786us/step - loss: 0.7130
Epoch 6/100
4/4 [==============================] - 0s 799us/step - loss: 0.6555
Epoch 7/100
4/4 [==============================] - 0s 895us/step - loss: 0.5824
Epoch 8/100
4/4 [==============================] - 0s 821us/step - loss: 0.7943
Epoch 9/100
4/4 [==============================] - 0s 882us/step - loss: 0.7068
Epoch 10/100
4/4 [==============================] - 0s 816us/step - loss: 0.9541
Epoch 11/100
4/4 [==============================] - 0s 840us/step - loss: 0.6570
Epoch 12/100
4/4 [==============================] - 0s 923us/step - loss: 0.9805
Epoch 13/100
4/4 [=========================

In [14]:
# 7. 모델 테스트하기
test_data = np.array([[0,1], [0,0], [1,1]]) # 0,0,1

print(model.predict(test_data))
print(model.predict_classes(test_data))

[[0.20966637]
 [0.38434976]
 [0.30714148]]
[[0]
 [0]
 [0]]


In [9]:
# optimizer 조정
# ''제외한 sgd 하면 ('sgd': defaluted sgd)

model1 = keras.Sequential()

model1.add(Dense(input_dim = 2, units = 1)) #feature = 0 or 1(2개)
model1.add(Activation('sigmoid'))
model1.summary()

sgd = keras.optimizers.SGD(lr = 0.1)

model1.compile(loss = 'binary_crossentropy', optimizer = sgd)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 모델 학습하기
model1.fit(X, y,
          batch_size = 1, # 1개마다 답확인
          epochs = 100) # 100번 반복 => 4개  데이터 * 100 

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 1.0336
Epoch 2/100
4/4 [==============================] - 0s 815us/step - loss: 0.8484
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 0.6264
Epoch 4/100
4/4 [==============================] - 0s 902us/step - loss: 0.8276
Epoch 5/100
4/4 [==============================] - 0s 845us/step - loss: 0.6012
Epoch 6/100
4/4 [==============================] - 0s 833us/step - loss: 0.6578
Epoch 7/100
4/4 [==============================] - 0s 784us/step - loss: 0.6446
Epoch 8/100
4/4 [==============================] - 0s 868us/step - loss: 0.7573
Epoch 9/100
4/4 [==============================] - 0s 1ms/step - loss: 0.5709
Epoch 10/100
4/4 [==============================] - 0s 802us/step - loss: 0.5714
Epoch 11/100
4/4 [==============================] - 0s 876us/step - loss: 0.5607
Epoch 12/100
4/4 [==============================] - 0s 2ms/step - loss: 0.6952
Epoch 13/100
4/4 [===========================

In [13]:
# 모델 테스트하기
test_data = np.array([[0,1], [0,0], [1,1]]) # 0,0,1

print(model1.predict(test_data))
print(model1.predict_classes(test_data))

[[0.25589448]
 [0.05871806]
 [0.6313647 ]]
[[0]
 [0]
 [1]]


In [16]:
# 가중치 확인
print('model:', model.get_weights())
print('model1:', model1.get_weights())

model: [array([[ 0.51342  ],
       [-0.8558115]], dtype=float32), array([-0.47112602], dtype=float32)]
model1: [array([[1.6054935],
       [1.7070779]], dtype=float32), array([-2.7744956], dtype=float32)]


In [18]:
? keras.optimizers.SGD